AWSTemplateFormatVersion: 2010-09-09
Description: Outputs practice

Parameters:
  MyKeyName:
    Description: Select the Key Name
    Type: AWS::EC2::KeyPair::KeyName
  MyEnvironmentName:
    Description: Select the environment 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: must be development or production      

Mappings:     
  MyRegionMap:
    us-east-1:
      HVM64: ami-0e8a34246278c21e4
    us-west-1:
      HVM64: ami-0e8a34246278c21e4
  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small   

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: 
        - !Ref MyDevGlobalSecurityGroup

  MyDevGlobalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Dev environment Global Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
# Available attributes of each AWS Resouce
# https://theburningmonk.com/cloudformation-ref-and-getatt-cheatsheet/
# Output 1
  MyInstanceId: 
    Description: My instance ID
    Value: !Ref MyVMInstance
# Output 2
  MyDNSName:
    Description: Public DNS Name
    Value: !GetAtt MyVMInstance.PublicDnsName
# Output 3
  MyInstanceAvailabilityZone:
    Description: Instance AZ Zone 
    Value: !GetAtt MyVMInstance.AvailabilityZone
    # Export 1
    Export: 
    # !Sub function essentially assign the new stack name
    # In this case, the Exported name of the stack would be StackName and "-InstanceAz"
      Name: !Sub "${AWS::StackName}-InstanceAz"
# Output 4
  MyDevSecurityGroup: 
    Description: SG Created for Dev Environment
    Value: !Ref MyDevGlobalSecurityGroup
    # Export 2
    Export:
      Name: MyDevSSHGlobalSG
# Output 5
  MySecurityGroupId:
    Description: SG Group ID
    Value: !GetAtt MyDevGlobalSecurityGroup.GroupId