AWSTemplateFormatVersion: 2010-09-09
# Tips: 
  # We can't delte a stack if another stack references one of its outputs
  # We can't modify or remove an output value that is referenced by another stack
Description: Outputs practice

Parameters:
  MyKeyName:
    Description: Select the Key Name
    Type: AWS::EC2::KeyPair::KeyName
  MyEnvironmentName:
    Description: Select the environment 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: must be development or production      

Mappings:     
  MyRegionMap:
    us-east-2:
      HVM64: ami-0cd3dfa4e37921605
    us-west-1:
      HVM64: ami-0ec6517f6edbf8044
  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small   

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      # Cross-Referencing resources
      SecurityGroups: 
      # Importing value of SG and AZ from previous stack
      # Pre-Req: it requies to have referenced Resources up and running
      # ImportValue will not create these resources, it is just a reference from other stacks
      # based on variable name (must have unique name)
        - !ImportValue MyDevSSHGlobalSG
      AvailabilityZone: !ImportValue cf-InstanceAz


