AWSTemplateFormatVersion: 2010-09-09
Description: Outputs practice

Parameters:
  MyKeyName:
    Description: Select the Key Name
    Type: AWS::EC2::KeyPair::KeyName
  MyEnvironmentName:
    Description: Select the environment 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: must be development or production      

Mappings:     
  MyRegionMap:
    us-east-1:
      HVM64: ami-0e8a34246278c21e4
    us-west-1:
      HVM64: ami-0e8a34246278c21e4
  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small   

Conditions:
# If dev environment is selected from paramenter, create DevSecurityGroup
# Corresponding lines of code are in line 51 and line 84
  CreateDevSecurityGroup: !Equals [!Ref MyEnvironmentName, dev]

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref MyEnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      # if prod is selected we don't have condition to create a SG so entire Template fails 
      # In order to runt the template we have to specify a case when prod is selected 
      # at that point assign a NoValue Pseudo value "NoValue" to the prod SG.
      SecurityGroups: !If [CreateDevSecurityGroup, [!Ref MyDevGlobalSecurityGroup], !Ref 'AWS::NoValue']
    
  MyDevGlobalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateDevSecurityGroup
    Properties:
      GroupDescription: My Dev environment Global Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

Outputs:
# Output 1
  MyInstanceId: 
    Description: My instance ID
    Value: !Ref MyVMInstance
# Output 2
  MyDNSName:
    Description: Public DNS Name
    Value: !GetAtt MyVMInstance.PublicDnsName
# Output 3
  MyInstanceAvailabilityZone:
    Description: Instance AZ Zone 
    Value: !GetAtt MyVMInstance.AvailabilityZone
    # Export 1
    Export: 
      Name: !Sub "${AWS::StackName}-InstanceAz"
# Output 4
  MyDevSecurityGroup: 
    Description: SG Created for Dev Environment
    Value: !Ref MyDevGlobalSecurityGroup
# if DevSecurityGroup is created, create an Output
    Condition: CreateDevSecurityGroup
    # Export 2
    Export:
    # The output name would be StackName-MyMyDevSSHGlobalSG
      Name: !Join ["-", [!Ref 'AWS::StackName', MyDevSSHGlobalSG]]
