AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01bc990364452ab3e
      InstanceType: t2.micro
      KeyName: keypair
      SecurityGroups: 
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My NEW SSH Security Groups
      # OutBound is all open in custom Security Groups
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0