AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter Implementation

Parameters: 
  MyKeyName:
    Description: Select the desired key name
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01bc990364452ab3e
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups: 
        - default
        - !Ref SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My NEW SSH Security Groups
      # OutBound is all open in custom Security Groups
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0