AWSTemplateFormatVersion: 2010-09-09

Parameters:
# Parameters will be sorted in Alphabetical order in Console by default 
# But if Parameters are grouped in Metadata section, it will be 
# groupped based on Label Description (refer to Line No 44 & 51)
  EnvironmentName:
    Description: Select the environment 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: must be development or production      
  InstanceType: 
    Description: Select the ec2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
  KeyName:
    Description: Key name to SSH to VM's. 
    Type: AWS::EC2::KeyPair::KeyName
  AvailabilityZone:
    Description: select the availability zone
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c

Conditions:
  CreateEIPForProd: !Equals [!Ref EnvironmentName, prod]

Metadata:
# Metadata is essentially for how certain parameters and description are 
# displayed in console during resources creation. 
# it doesn't have anything to do with resources creation and management.
  AWS:CloudFormation::Interface:
    ParameterGroups:
    # Account for all parameters that are created above for Aws Resouces (In our example, EC2)

      - Label: 
          default: "EC2 Instance Configuration" 
        Parameters: 
          - InstaneType
          - KeyName
          - AvailabilityZone 
        # Why EnvironmentName is separate?? because it is referred in Conditions??
      - Label: 
          default: "Environment Configuration" 
        Parameters: 
          - EnvironmentName
    ParameterLabels:
    # Each parameters in Metadata can have labels. 
    # it is just a descritive name for metadata parameters
      EnvironmentName:
        default: "Environment we choose to create instance"
      KeyName: 
        default: "Once KeyName is selected, cannot change it unless instances replace"
  
Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05c13eab67c5d8861
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref AvailabilityZone
    
  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Properties: 
      InstanceId: !Ref MyVMInstance
          
