AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack Template

Parameters:
  VPCId:
    Description: Create Security group in this resp. VPC
    Type: AWS::EC2::VPC::Id
Resources: 
  DevSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Dev Apps Security Group
      SecurityGroupIngress:
        - IpPortocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpPortocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCId
Outputs:
  DevSGGroupId:
    Description: Dev Security 
    Value: !Ref DevSecurityGroup
